### ISSUE TITLE
Todo App 요구사항 명세서 작성

### ISSUE THREAD

**Issue by NtoZero** [NtoZero/cos_todo#1]
### 만들고자 하는 기능이 무엇인가요?
    ex) Todo 생성 기능

    ### 해당 기능을 구현하기 위해 할 일이 무엇인가요?
    1. [ ] Job1 : Repository, Service 작성
    2. [ ] Job2 : Entity, Mapper, DTO 작성
    3. [ ] Job3 : Controller 작성

    ### 예상 작업 시간
    ex) 1h 30m

**Comment by NtoZero** [comment]
Complete

**Comment by NtoZero** [comment]
Completed
